6.

In [ ]:
students = [
    {"name:","민수" ,"score:",79},
    {"name:","지영" ,"score:",80},
    {"name:","현우" ,"score:",89},
    {"name:","수빈" ,"score:",90},
    {"name:","원빈" ,"score:",91},
]

for student in students:

In [7]:
#6. 학생 성적을 세 단계로 분류하기
#요구사항
students = [

    {"name":"민수" ,"score":79},
    {"name":"지영" ,"score":80},
    {"name":"현우" ,"score":89},
    {"name":"수빈" ,"score":90},
    {"name":"원빈" ,"score":91},
  
]

# print(type(students))
# print(students)

# 모든 학생을 한 명씩 확인하여 다음 기준으로 결과를 정합니다.
for student in students:
    
    if student["score"] >= 90:
        print(student["name"],student["score"],"우수")
    
    elif student["score"] >= 80:
        print(student["name"],student["score"],"합격")
    else:
        print(student["name"],student["score"],"보완필요")
 

# • 90점 이상이면 우수

# • 80점 이상이면 합격
  
# • 그 외에는 보완 필요

# • 모든 학생의 이름, 점수, 결과를 확인할 수 있어야 합니다.

민수 79 보완필요
지영 80 합격
현우 89 합격
수빈 90 우수
원빈 91 우수

In [10]:
#7. 쇼핑몰 주문의 배송 등급 결정하기


customers = [
    {"name": "민수" ,"order_price": 49000, "grade" : "일반"},
    {"name":"지영","order_price":50000,"grade":"VIP"},
    {"name":"현우","order_price":99000,"grade":"일반"},
    {"name":"수빈","order_price":100000,"grade":"VIP"},
    {"name":"원빈","order_price":120000,"grade":"일반"},
]

#모든 주문을 하나씩 확인하고 다음 기준으로 배송 결과를 정합니다.
for customer in customers:
    order_price = customer["order_price"]
    name = customer["name"]
    grade = customer["grade"]
    ship_type =""

    if order_price >= 100000 and grade =="VIP":
        ship_type ="VIP 유선배송"
        # print(f"{name}님의 배송방법은 VIP 우선배송")
    elif order_price >= 50000 and grade =="VIP":
        ship_type ="무료배송"
        # print(f"{name}님은 무료배송")
    else :
        ship_type ="일반배송"
        # print(f"{name}님은 일반배송")    

    print(f"{name}의 배송결과는{ship_type} 입니다. 주문금액: {order_price}원, 회원등급:{grade}")

# • 주문금액이 100,000원 이상이면서 회원등급이 VIP이면 VIP 우선배송

# • 그렇지 않더라도 주문금액이 50,000원 이상이거나 회원등급이 VIP이면 무료배송

# • 나머지는 일반배송

# • 모든 고객의 고객명, 주문금액, 회원등급, 배송 결과를 확인할 수 있어야 합니다.

민수의 배송결과는일반배송 입니다. 주문금액: 49000원, 회원등급:일반
지영의 배송결과는무료배송 입니다. 주문금액: 50000원, 회원등급:VIP
현우의 배송결과는일반배송 입니다. 주문금액: 99000원, 회원등급:일반
수빈의 배송결과는VIP 유선배송 입니다. 주문금액: 100000원, 회원등급:VIP
원빈의 배송결과는일반배송 입니다. 주문금액: 120000원, 회원등급:일반

In [18]:
#상품 상태와 추천 여부 함께 판단하기 (새로운 컬럼까지 더해서) csv파일로 저장하기. 
import csv

products = [
    {"name":"키보드","rating":4.8,"stock":12, "status":"판매중"},
    {"name":"키보드","rating":4.6,"stock":3, "status":"판매중"},
    {"name":"키보드","rating":4.2,"stock":0, "status":"판매중"},
    {"name":"키보드","rating":4.9,"stock":8, "status":"판매중지"},
    {"name":"키보드","rating":3.8,"stock":10, "status":"판매중"},
] 


# 모든 상품을 하나씩 확인하여 다음 기준으로 상품 결과를 정합니다.
for product in products:
    name = product["name"]
    rating = product["rating"]
    stock = product["stock"]
    status = product["status"]

    if status != "판매중" or stock <= 0:
        result = "판매불가"
    elif rating >= 4.5 and stock >= 5:
        result = "추천"
    elif rating >= 4.0:
        result = "일반"
    else:
        result = "관심필요"

    #딕셔너리에 result 필드 추가. 값add
    product["result"] = result    

    print(f"상품명 : {name}, 평점: {rating}, 재고:{stock}, 판매상태:{status}, 결과:{is_recommended}")        

with open("products_result.csv", "w", newline="", encoding="utf-8-sig") as file:
    fieldnames = ["name", "rating", "stock", "status", "result"]
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    writer.writeheader()
    writer.writerows(products)
 

# 판매상태가 판매중이 아니거나 재고가 0 이하이면 판매불가

# • 위 조건에 해당하지 않으면서 평점이 4.5 이상이고 재고가 5개 이상이면 추천

# • 위 조건에 해당하지 않으면서 평점이 4.0 이상이면 일반

# • 나머지는 관심 필요

# • 모든 상품의 상품명, 평점, 재고, 판매상태, 결과를 확인할 수 있어야 합니다.

상품명 : 키보드, 평점: 4.8, 재고:12, 판매상태:판매중, 결과:관심필요
상품명 : 키보드, 평점: 4.6, 재고:3, 판매상태:판매중, 결과:관심필요
상품명 : 키보드, 평점: 4.2, 재고:0, 판매상태:판매중, 결과:관심필요
상품명 : 키보드, 평점: 4.9, 재고:8, 판매상태:판매중지, 결과:관심필요
상품명 : 키보드, 평점: 3.8, 재고:10, 판매상태:판매중, 결과:관심필요

In [1]:
import pandas as pd
products_df = pd.read_csv("products_result.csv", encoding="utf-8-sig")
products_df

  name  rating  stock status result
0  키보드     4.8     12    판매중     추천
1  키보드     4.6      3    판매중     일반
2  키보드     4.2      0    판매중   판매불가
3  키보드     4.9      8   판매중지   판매불가
4  키보드     3.8     10    판매중   관심필요

In [2]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   rating  5 non-null      float64
 2   stock   5 non-null      int64
 3   status  5 non-null      str
 4   result  5 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 473.0 bytes

In [3]:
products_df.head()

  name  rating  stock status result
0  키보드     4.8     12    판매중     추천
1  키보드     4.6      3    판매중     일반
2  키보드     4.2      0    판매중   판매불가
3  키보드     4.9      8   판매중지   판매불가
4  키보드     3.8     10    판매중   관심필요

In [4]:
products_df["name"].value_counts()

name
키보드    5
Name: count, dtype: int64

In [5]:
products_df["rating"].value_counts()

rating
4.8    1
4.6    1
4.2    1
4.9    1
3.8    1
Name: count, dtype: int64

In [6]:
products_df["stock"].value_counts()

stock
12    1
3     1
0     1
8     1
10    1
Name: count, dtype: int64

In [7]:
products_df["status"].value_counts()

status
판매중     4
판매중지    1
Name: count, dtype: int64

In [8]:
products_df["result"].value_counts()

result
판매불가    2
추천      1
일반      1
관심필요    1
Name: count, dtype: int64

In [9]:
for column in products_df.columns:
    print(f"===== {column} =====")
    print(products_df[column].value_counts())
    print()

===== name =====
name
키보드    5
Name: count, dtype: int64

===== rating =====
rating
4.8    1
4.6    1
4.2    1
4.9    1
3.8    1
Name: count, dtype: int64

===== stock =====
stock
12    1
3     1
0     1
8     1
10    1
Name: count, dtype: int64

===== status =====
status
판매중     4
판매중지    1
Name: count, dtype: int64

===== result =====
result
판매불가    2
추천      1
일반      1
관심필요    1
Name: count, dtype: int64